-- SPDX-License-Identifier: LicenseRef-Proprietary
--
-- Copyright (c) 2026 Alexandre Boutrik. All Rights Reserved.
--
-- CONFIDENTIAL AND PROPRIETARY.
--
-- The intellectual and technical concepts contained herein are proprietary
-- to Alexandre Boutrik and are protected by trade secret, copyright and
-- patent law. Dissemination of this information or reproduction of this
-- material is strictly forbidden unless prior written permission is obtained.
--
-- Unauthorized access, use, reproduction, or distribution of this file is
-- strictly prohibited.
--
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER "AS IS" AND ANY EXPRESS
-- OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
-- WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
-- NON-INFRINGEMENT ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE
-- LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
-- CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
-- SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
-- INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
-- CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
-- ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
-- POSSIBILITY OF SUCH DAMAGE.

{- |
Module      : Dassh.Types
Description : Core data types and C-struct memory mappings.

This module defines the data models used across dassh.
It includes the application's UI state, SSH session metadata, and
defines the memory layout via the 'Storable' typeclass to deserialize
the eBPF ring buffer C structs via FFI.
-}
module Dassh.Types (
    SshSession (..),
    AppState (..),
    EbpfEvent (..),
    DasshEvent (..),
) where

import Data.ByteString (ByteString)
import Data.ByteString.Internal (create)
import Data.Word (Word8)
import Foreign.C.Types (CUInt (..))
import Foreign.Marshal.Utils (copyBytes)
import Foreign.Ptr (Ptr, castPtr, plusPtr)
import Foreign.Storable (Storable (..))

{- |
Represents metadata and the actively captured output for a single
SSH session. This record acts as the primary data store for the
dashboard panes.
-}
data SshSession = SshSession
    { sessionPid :: !Int
    -- ^ Root Process ID of the SSH session shell.
    , sessionTty :: !String
    -- ^ Assigned TTY device (e.g., "/dev/pts/1") extracted from /proc.
    , sessionBuffer :: !ByteString
    -- ^ Sanitized, safe-to-render terminal output.
    , sessionCursor :: !Int
    {- ^ 1D cursor offset from the end of the buffer, used to emulate
    non-destructive backspaces and inline text overrides.
    -}
    , sessionStaging :: !ByteString
    {- ^ Line-buffered staging area to safely filter stdout pipes without
    chunk fragmentation
    -}
    }
    deriving (Show, Eq)

{- |
The core application state managed by the Brick UI event loop.
It tracks all active sessions and manages viewport interactions.
-}
data AppState = AppState
    { appSessions :: ![SshSession]
    -- ^ List of all currently active and monitored SSH sessions.
    , appSelectedIdx :: !Int
    -- ^ Index of the currently focused pane
    , appExpanded :: !Bool
    {- ^ A flag indicating whether the selected session is expanded
    into the full-screen view.
    -}
    }
    deriving (Show, Eq)

{- |
Custom events pushed asynchronously to the Brick event loop.
These are generated by the background eBPF polling thread or the
discovery thread.
-}
data DasshEvent
    = NewPayload EbpfEvent
    | RefreshSessions [SshSession]
    deriving (Show, Eq)

{- |
Represents the raw, serialized C struct payload pushed by the kernel
eBPF ring buffer.
-}
data EbpfEvent = EbpfEvent
    { eventRootPid :: !CUInt
    -- ^ The Root Session PID.
    , eventActualPid :: !CUInt
    -- ^ The actual PID of the process generating the event.
    , eventFd :: !CUInt
    -- ^ The File Descriptor (e.g., 1 for stdout, 2 for stderr).
    , eventPayload :: !ByteString
    -- ^ Raw byte stream captured from the kernel tracepoint.
    }
    deriving (Show, Eq)

-- | The size of the fixed payload buffer in the C header.
payloadSize :: Int
payloadSize = 256

{- |
Storable instance mapping the Haskell 'EbpfEvent' to the
C 'struct ebpf_event'.
Aligned to 4 bytes to match standard C ABI padding rules.
-}
instance Storable EbpfEvent where
    sizeOf _ = 268
    alignment _ = 4

    peek ptr = do
        rootPid <- peek (castPtr ptr :: Ptr CUInt)
        actualPid <- peek (castPtr (ptr `plusPtr` 4) :: Ptr CUInt)
        fd <- peek (castPtr (ptr `plusPtr` 8) :: Ptr CUInt)

        let payloadPtr = castPtr (ptr `plusPtr` 12) :: Ptr Word8

        payload <- create payloadSize $ \destPtr ->
            copyBytes destPtr payloadPtr payloadSize

        return $ EbpfEvent rootPid actualPid fd payload

    -- This application is a consumer of eBPF events.
    -- We never write structs back into the ring buffer.
    poke _ _ = error "poke is not implemented for EbpfEvent (Read-only)"
